### PR TITLE
add ondisposeonset

### PR DESCRIPTION
**Pull request by Tbolp**

### CODE REVIEW

**Comment by roccomuso** [comment]
Are you using this option? is it really useful?

**Comment by Tbolp** [comment]
Yes, i use it. I don't want to call dispose function when i update value, so i find this option in lru and add it.

**Comment by balakine** [comment]
Having dispose without noDisposeOnSet is utterly pointless, since every session read calls set. Please merge.

**Comment by roccomuso** [comment]
Thanks for PR. Shipping it with next patch release.

**Pull request merged**
