### PR TITLE
Fix types for typescript in strict mode

### PR DESCRIPTION
**Pull request by vdechef**
Cf. #22

### CODE REVIEW

**Comment by roccomuso** [comment]
thanks

**Comment by vdechef** [comment]
@roccomuso would it be possible to generate and publish a new release on npm with this fix ?
Thanks

**Comment by roccomuso** [comment]
done `v1.6.5`

**Comment by roccomuso** [comment]
Not sure if related to this PR.
But now the package is broken if used like this:

```js
import session from 'express-session';
import MemoryStore from 'memorystore';
const mStore = MemoryStore(session);
```

**Comment by roccomuso** [comment]
looks like this break something https://github.com/roccomuso/memorystore/issues/26#issue-835424245
Please investigate or I should revert the PR

**Pull request merged**
