### PR TITLE
fix: Handling touch session that is previously removed

### PR DESCRIPTION
**Pull request by shayantabatabaee**
Hi, 

Due to this issue #13 I made these changes and commit to the repository, please kindly review the code and accept the pull request If you find it useful.

thanks you,
Shayan Tabatabaee

### CODE REVIEW

**Comment by roccomuso** [comment]
not sure this is needed.
The error is catched anyway,

**Comment by shayantabatabaee** [comment]
Yes the error is catched, but the error is thrown from memorystore module is meaningless, `unable to parse JSON u at position 0` , and it is hard to trace problem. So why deleted session should be touched ?

**Comment by shayantabatabaee** [comment]
@roccomuso : Any update ?

**Comment by roccomuso** [comment]
I'm publishing new version now

**Pull request merged**
